### ISSUE TITLE
CONTRIBUTING.md and CONTRIBUTORS.md should be separated.

### ISSUE THREAD

**Issue by Diptonil** [MaheshDoiphode/hacktoberfest-LeetCode-2022#141]
CONTRIBUTING.md is a file used to denote the guidelines to contribute to a certain project.
CONTRIBUTORS.md should enumerate all the names of the people who have contributed.
This convention is not being followed here for some reason.
I will fix this issue, please accept my PR.

**Comment by Diptonil** [comment]
PR #142 solves this issue. I request the maintainer to approve my PR or suggest any changes and close this Issue.

**Comment by MaheshDoiphode** [comment]
Thanks for solving this issue bro. This is the first time I am hosting a repository for hactoberfest due to which some things were/are missing. Appreciate your help towards the repository.

**Comment by MaheshDoiphode** [comment]
This repo is no longer under consideration for the hactoberfest event.
